# Generated by Django 4.2.7 on 2023-11-09 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('niche_score', models.BigIntegerField()),
                ('website_url', models.CharField(max_length=300)),
                ('linkedin_url', models.CharField(max_length=300)),
            ],
        ),
    ]
